###################
# devcli configuration
#
# The following section is for global options for devcli
# this name space should not be used by dynamic commands
# to avoid conflicts
[devcli]

# whether devcli should load its own subcommands
enable_builtin_commands = true

#############################
# op command is a shortcut for some OnePassword cli calls
[devcli.commands.op]

# The account ID you want to use. 1Password can be logged in
# more than one account, you can use `op account list` to
# find your account id.
account = "OUR_ACCOUNT_ID"

# Optional: which vault use by default
# You can list your vaulst with `op vault list`
# by default vault is set to 'Private'
# vault = "Private"

#############################
# url command is a shortcut for URLs that you use often
# each 'key' in this configuration is an alias
# for the URL you want to use
[devcli.commands.url]

devcli = "https://github.com/mvaltas/devcli"
